version: "3.2"
services:
    db:
      image: mysql:8.0.33
      volumes:
        - db_data:/var/lib/mysql2
        - ./mysql-dump:/docker-entrypoint-initdb.d
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: hh
      ports:
        - 3307:3306

    web_app:
      restart: always
      depends_on:
        - db
      build: ./
      command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
      volumes:
        - ./src:/var/www/app/src
        - ./package.json:/var/www/app/package.json
      ports:
        - 3001:3000
        - 9229:9229

volumes:
    db_data: {}
